# Generated by Django 5.0.10 on 2025-01-05 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mstcomponent',
            old_name='component_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='mstcategory',
            name='component_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpmponent_categories', to='masters.mstcomponent'),
        ),
        migrations.AlterField(
            model_name='mstdesignoptions',
            name='design_option_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mstcategory',
            unique_together={('category_name', 'component_Id')},
        ),
        migrations.AlterUniqueTogether(
            name='mstsubcategory',
            unique_together={('sub_category_name', 'category_Id')},
        ),
    ]
