# Generated by Django 5.0.10 on 2025-01-05 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_rename_component_id_mstcomponent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstSubCategoryRelations',
            fields=[
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_design_options', models.BooleanField(default=False)),
                ('is_sub_2_category', models.BooleanField(default=False)),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='masters.mstsubcategory', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MstSubCategoryTwo',
            fields=[
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_2_category_name', models.CharField(max_length=255)),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories2', to='masters.mstsubcategory')),
            ],
            options={
                'unique_together': {('sub_2_category_name', 'sub_category_id')},
            },
        ),
    ]
