# Generated by Django 5.0.10 on 2025-01-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_logged_out',
            field=models.BooleanField(default=True),
        ),
    ]
