# Generated by Django 5.0.10 on 2025-01-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('CADesigner', 'CADesigner'), ('Approver', 'Approver'), ('Verifier', 'Verifier')], default='CADesigner', max_length=20, null=True),
        ),
    ]
