# Generated by Django 5.0.10 on 2025-01-06 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CADDesignTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opp_number', models.CharField(max_length=255, unique=True)),
                ('opu_number', models.CharField(max_length=255, unique=True)),
                ('edu_number', models.CharField(max_length=255, unique=True)),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('part_number', models.CharField(max_length=255, unique=True)),
                ('revision_number', models.CharField(max_length=255, unique=True)),
                ('pcb_specifications', models.JSONField()),
                ('smt_design_options', models.JSONField()),
                ('design_rules_follow', models.JSONField()),
                ('component_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_templates', to='masters.mstcomponent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
