# Generated by Django 4.2.17 on 2025-01-02 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ManyToManyField(related_name='design_options', to='right_to_draw.category')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('route', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opp_number', models.CharField(max_length=100)),
                ('opu_number', models.CharField(max_length=100)),
                ('edu_number', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='right_to_draw.category')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='right_to_draw.component')),
                ('design_options', models.ManyToManyField(related_name='specifications', to='right_to_draw.designoption')),
            ],
        ),
        migrations.CreateModel(
            name='DesignRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_description', models.TextField()),
                ('design_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_rules', to='right_to_draw.designoption')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='right_to_draw.component'),
        ),
    ]
