# Generated by Django 4.2.17 on 2025-01-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('right_to_draw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='component',
        ),
        migrations.RemoveField(
            model_name='designoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='designrule',
            name='design_option',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='category',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='component',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='design_options',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='DesignOption',
        ),
        migrations.DeleteModel(
            name='DesignRule',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
