# Generated by Django 5.0.10 on 2025-01-05 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_rename_component_id_mstcomponent_id_and_more'),
        ('right_to_draw', '0002_remove_category_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CADDesignTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opp_number', models.CharField(max_length=255, unique=True)),
                ('opu_number', models.CharField(max_length=255, unique=True)),
                ('edu_number', models.CharField(max_length=255, unique=True)),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('part_number', models.CharField(max_length=255, unique=True)),
                ('revision_number', models.CharField(max_length=255, unique=True)),
                ('pcb_specifications', models.JSONField()),
                ('smt_design_options', models.JSONField()),
                ('design_rules_follow', models.JSONField()),
                ('component_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_templates', to='masters.mstcomponent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
